### ISSUE TITLE
the reading logo has disappeared

### ISSUE THREAD

**Issue by Garis24** [Zalk0/DeezerRPC#88]
currently: ![image](https://github.com/Zalk0/DeezerRPC/assets/115723322/a48e011e-5ed1-4f8a-bbcd-bd85d38663d9)
on the main bank: ![image](https://github.com/Zalk0/DeezerRPC/assets/115723322/7f115f7c-3a3e-497a-9771-f46a77a79666)

**Comment by Zalk0** [comment]
Hey, I just fixed it, no update needed.
I had forgotten to upload the "status" images in the Discord Developer Application I created.
Thanks for reporting
